name: podiinyk
description: A cross-platform mobile app for Ukrainian students.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^2.17.5

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0

  flutter_hooks: ^0.18.5
  hooks_riverpod: ^1.0.4

  cloud_firestore: ^3.2.1
  firebase_auth: ^3.6.1
  firebase_core: ^1.19.1
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
