name: podiinyk
description: A cross-platform mobile app for Ukrainian students.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^2.17.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
