// do: move and rewrite the file
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
		show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
	static FirebaseOptions get currentPlatform {
		if (kIsWeb) {
			throw UnsupportedError(
				'DefaultFirebaseOptions have not been configured for web - '
				'you can reconfigure this by running the FlutterFire CLI again.',
			);
		}
		switch (defaultTargetPlatform) {
			case TargetPlatform.android:
				return android;
			case TargetPlatform.iOS:
				return ios;
			case TargetPlatform.macOS:
				throw UnsupportedError(
					'DefaultFirebaseOptions have not been configured for macos - '
					'you can reconfigure this by running the FlutterFire CLI again.',
				);
			case TargetPlatform.windows:
				throw UnsupportedError(
					'DefaultFirebaseOptions have not been configured for windows - '
					'you can reconfigure this by running the FlutterFire CLI again.',
				);
			case TargetPlatform.linux:
				throw UnsupportedError(
					'DefaultFirebaseOptions have not been configured for linux - '
					'you can reconfigure this by running the FlutterFire CLI again.',
				);
			default:
				throw UnsupportedError(
					'DefaultFirebaseOptions are not supported for this platform.',
				);
		}
	}

	static const FirebaseOptions android = FirebaseOptions(
		apiKey: 'AIzaSyCYU4XKNnm2U4r3qrL6Cjjk3HDBjQkiU9A',
		appId: '1:764008713279:android:0c4ae02a26d6245e26fc8a',
		messagingSenderId: '764008713279',
		projectId: 'podiinyk',
		storageBucket: 'podiinyk.appspot.com',
	);

	static const FirebaseOptions ios = FirebaseOptions(
		apiKey: 'AIzaSyBBgfal0_VyL1exqbvSnQpdSqlCpk2Nvqw',
		appId: '1:764008713279:ios:5920ea2baf7e6a9226fc8a',
		messagingSenderId: '764008713279',
		projectId: 'podiinyk',
		storageBucket: 'podiinyk.appspot.com',
		iosClientId: '764008713279-r6i3uhjp36gopeq2jlrglivq7a2jabfd.apps.googleusercontent.com',
		iosBundleId: 'kraianyn.podiinyk',
	);
}
